# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Informacija"
  identifier = "informacija"
  url = "informacija/"
  weight = 10

[[main]]
  name = "Apie projektą"
  parent = "informacija"
  identifier = "apie-projekta"
  url = "informacija/apie-projekta/"

[[main]]
  name = "Kaip įsigyti"
  parent = "informacija"
  identifier = "kaip-isigyti"
  url = "informacija/kaip-isigyti/"

[[main]]
  name = "Talentai"
  parent = "informacija"
  identifier = "talentai"
  url = "informacija/talentai/"

[[main]]
  name = "Paraiška"
  parent = "informacija"
  identifier = "paraiska"
  url = "informacija/paraiska/"

[[main]]
  name = "Vilnius"
  identifier = "vilnius"
  url = "#posts"
  weight = 20

[[main]]
  name = "2014"
  parent = "vilnius"
  identifier = "vilnius-2014"
  url = "vilnius/2014"

[[main]]
  name = "2015"
  parent = "vilnius"
  identifier = "vilnius-2015"
  url = "vilnius/2015"

[[main]]
  name = "2016"
  parent = "vilnius"
  identifier = "vilnius-2016"
  url = "vilnius/2016"

[[main]]
  name = "2017"
  parent = "vilnius"
  identifier = "vilnius-2017"
  url = "vilnius/2017"

[[main]]
  name = "2018"
  parent = "vilnius"
  identifier = "vilnius-2018"
  url = "vilnius/2018"

[[main]]
  name = "2019"
  parent = "vilnius"
  identifier = "vilnius-2019"
  url = "vilnius/2019"

[[main]]
  name = "Kaunas"
  url = "404"
  identifier = "kaunas"
  weight = 30

[[main]]
  name = "2016"
  parent = "kaunas"
  identifier = "kaunas-2016"
  url = "kaunas/2016/"

[[main]]
  name = "2017"
  parent = "kaunas"
  identifier = "kaunas-2017"
  url = "404"

[[main]]
  name = "2019"
  parent = "kaunas"
  identifier = "kaunas-2019"
  url = "404"

[[main]]
  name = "Klaipėda"
  identifier = "klaipeda"
  url = "404"
  weight = 40

[[main]]
  name = "2016"
  parent = "klaipeda"
  identifier = "klaipeda-2016"
  url = "404"

[[main]]
  name = "2017"
  parent = "klaipeda"
  identifier = "klaipeda-2017"
  url = "klaipeda/2017"

[[main]]
  name = "2018"
  parent = "klaipeda"
  identifier = "klaipeda-2018"
  url = "klaipeda/2018"

[[main]]
  name = "2019"
  parent = "klaipeda"
  identifier = "klaipeda-2019"
  url = "404"

[[main]]
  name = "Šiauliai"
  identifier = "siauliai"
  url = "404"
  weight = 50

[[main]]
  name = "2016"
  parent = "siauliai"
  identifier = "siauliai-2016"
  url = "siauliai/2016/"

[[main]]
  name = "2017"
  parent = "siauliai"
  identifier = "siauliai-2017"
  url = "siauliai/2017/"

[[main]]
  name = "2018"
  parent = "siauliai"
  identifier = "siauliai-2018"
  url = "404"

[[main]]
  name = "2019"
  parent = "siauliai"
  identifier = "siauliai-2019"
  url = "siauliai/2019/"

[[main]]
  name = "Marijampolė"
  identifier = "marijampole"
  url = "404"
  weight = 60

[[main]]
  name = "2016"
  parent = "marijampole"
  identifier = "marijampole-2016"
  url = "marijampole/2016/"

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
